# Generated by Django 6.0 on 2025-12-06 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_supplier_stockissue_supplierorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='stockissue',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='supplierorderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='supplierorderitem',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockissue',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='supplierorder',
            options={'ordering': ['-ordered_at']},
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='mpesa_phone',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='stockissue',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='stockissue',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='expected_date',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='supplierorder',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone used for payment, for example M-Pesa number.', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='reference',
            field=models.CharField(blank=True, help_text='Payment reference or transaction code.', max_length=100),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='issued_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.item'),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='ordered_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='quantity_ordered',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('PAYSTACK', 'Paystack'), ('CASH', 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.item'),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.supplier'),
        ),
        migrations.AddField(
            model_name='stockissue',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.client'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='SupplierOrderItem',
        ),
    ]
