# Generated by Django 6.0 on 2025-12-08 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_client_remove_stockissue_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockissue',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.client'),
        ),
        migrations.AlterField(
            model_name='stockissue',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.supplier'),
        ),
    ]
