"""
Django settings for itemo_IMS project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+884ro_4xbmmp-3swqu51)=-&^#8atxz_1r_zflngapc5erpq)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'store',
    'django_daraja',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'itemo_IMS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',    #added
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'itemo_IMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'  # for collectstatic later if needed

LOGIN_URL = "users:login"    #Where Django sends someone if they try to access a protected page without being logged in
LOGIN_REDIRECT_URL = 'store:main_menu'     #sends someone after they successfully login
# LOGIN_REDIRECT_URL = 'store:dashboard'
LOGOUT_REDIRECT_URL = 'landing'      #Django sends someone after they log out



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ========= M-Pesa Daraja sandbox configuration =========

MPESA_ENVIRONMENT = "sandbox"  # keep this as sandbox for testing
MPESA_CONSUMER_KEY = "ND65uGxA7UNXzenoaSqD3LzS5DSVzltnWyEWmnDo7xu2xKvh"
MPESA_CONSUMER_SECRET = "NRuWb0ZZJQuPDuKbfY44Q7aJlT5xDHkv9GPOoo2kEZz0NQFgnCSytRXolERYOmBT"
MPESA_SHORTCODE = "174379"
MPESA_EXPRESS_SHORTCODE = "174379"
MPESA_SHORTCODE_TYPE = "paybill"
MPESA_PASSKEY = "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
#
MPESA_CALLBACK_URL = "https://api.darajambili.com/express-payment"
#MPESA_CALLBACK_URL = "https://example.com/store/mpesa/callback/" # can be ngrok URL later, beware of security issues when using ngrok

# These two are mainly for B2C, but django_daraja wants them defined
MPESA_INITIATOR_USERNAME = "testapi"           # from test credentials
MPESA_INITIATOR_SECURITY_CREDENTIAL = "Safaricom123!!"  # or the one given
B2C_SHORTCODE = '174379'



